# Generated by Django 3.2.4 on 2021-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
